#!/bin/bash
#
# Exawind-builder configuration file.
# Generated by bootstrap script at 2020-09-10 14:10:20 MDT
# Documentation available at https://exawind-builder.readthedocs.io/en/latest/index.html
#
# Edit this to configure the build process with exawind-builder
#

#SPACK_ROOT=${EXAWIND_PROJECT_DIR}/spack
#SPACK_COMPILER=${SPACK_COMPILER:-${EXAWIND_COMPILER}}

#EXAWIND_MAKE_TYPE=ninja
#export PATH=/home/asharma/exawind//source/ninja:${PATH}

BUILD_TYPE=RELEASE     # [RELEASE, DEBUG, RELWITHDEBINFO]
ENABLE_OPENMP=OFF      # [ON, OFF]
ENABLE_CUDA=ON         # [ON, OFF]
BUILD_SHARED_LIBS=OFF  # Shared libraries

ENABLE_OPENFAST=OFF    # Enable OpenFAST TPL with Nalu-Wind
ENABLE_TIOGA=ON       # Enable TIOGA for overset connectivity
ENABLE_HYPRE=ON        # Enable HYPRE linear solvers with Nalu-Wind
ENABLE_FFTW=OFF        # Enable FFTW for ABL simulations

